title: Social Data Analysis and Visualization 2024
email: s233142@dtu.dk
description: >-
  This is a test for Week 7 of the course
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username: jesusdp-drcmr

# Build settings
# Theme
theme : minima

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

